:gen-class 설정, main 클래스를 java 클래스로 컴파일 할 수 있도록 함
> lein uberjar
Warning: specified :main without including it in :aot.
Implicit AOT of :main will be removed in Leiningen 3.0.0.
If you only need AOT for your uberjar, consider adding :aot :all into your
:uberjar profile instead.
Compiling hello-clojure.core
Warning: The Main-Class specified does not exist within the jar. It may not be executable as expected. A gen-class directive may be missing in the namespace which contains the main method, or the namespace has not been AOT-compiled.
Created C:\hello-clojure\target\hello-clojure-0.1.0-SNAPSHOT.jar
Created C:\hello-clojure\target\hello-clojure-0.1.0-SNAPSHOT-standalone.jar
> java -jar .\target\hello-clojure-0.1.0-SNAPSHOT-standalone.jar
Error: Could not find or load main class hello_clojure.core
Caused by: java.lang.ClassNotFoundException: hello_clojure.core